# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4f5506f44dc709ae1ffa9e87d2dd2c8d"
name = "Boiler_plate"
handle = "boiler_plate-1"
application_url = "https://7e99-182-188-239-12.ngrok-free.app"
embedded = true

[build]
automatically_update_urls_on_dev = false
dev_store_url = "quickstart-c0eb237e.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products"

[auth]
redirect_urls = [
  "https://7e99-182-188-239-12.ngrok-free.app/auth/callback",
  "https://7e99-182-188-239-12.ngrok-free.app/auth/shopify/callback",
  "https://7e99-182-188-239-12.ngrok-free.app/api/auth/callback"
]

[webhooks]
api_version = "2024-10"



[pos]
embedded = false
